case:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      port: 5433
      user: postgres
      password: postgres
      dbname: pokemon
      schema: public
      threads: 1
